<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'thephpcc\\greed\\d6' => '/D6.php',
                'thephpcc\\greed\\exception' => '/exceptions/Exception.php',
                'thephpcc\\greed\\greed' => '/Greed.php',
                'thephpcc\\greed\\outofrangeexception' => '/exceptions/OutOfRangeException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
